Script started on Wed 12 Apr 2017 09:01:29 AM PDT
]0;namir@namir: ~/lab8[01;32mnamir@namir[00m:[01;34m~/lab8[00m$ exit./collatz [6Pexit[Kvalgrind --leak-check=full ./lab8
==5514== Memcheck, a memory error detector
==5514== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==5514== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==5514== Command: ./lab8
==5514==

1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
1

Enter the number for the list: 2


Enter item at
1.) Head
2.) Tail
3.) Middle
1
Assigning 2.00 to head.
1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
3

List: 2.00

1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
4

Number of items in the list: 1

1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
5
Enter number to find: 2
2.00 has been found
1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
1

Enter the number for the list: 4


Enter item at
1.) Head
2.) Tail
3.) Middle
2
Assigning 4.00 to tail
1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
3

List: 2.00 4.00

1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
4

Number of items in the list: 2

1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
5
Enter number to find: 5
5.00 not found
1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
5
Enter number to find: 4
4.00 has been found
1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
1

Enter the number for the list: 6


Enter item at
1.) Head
2.) Tail
3.) Middle
3

Enter position: 2
Assigning 6.00 to middle.
1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
3

List: 2.00 6.00 4.00

1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
4

Number of items in the list: 3

1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
2

Enter number to be deleted: 6


1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
3

List: 2.00 4.00

1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
4

Number of items in the list: 2

1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
5
Enter number to find: 6
6.00 not found
1.) Enter a number
2.) Delete a number
3.) Print all numbers
4.) Tell how many items are in the list
5.) Find if a number in the list
6.) Quit
6
==5514==
==5514== HEAP SUMMARY:
==5514==     in use at exit: 16 bytes in 1 blocks
==5514==   total heap usage: 6 allocs, 5 frees, 2,112 bytes allocated
==5514==
==5514== 16 bytes in 1 blocks are definitely lost in loss record 1 of 1
==5514==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==5514==    by 0x400BD5: create_node (lab8.c:150)
==5514==    by 0x4009DB: main (lab8.c:85)
==5514==
==5514== LEAK SUMMARY:
==5514==    definitely lost: 16 bytes in 1 blocks
==5514==    indirectly lost: 0 bytes in 0 blocks
==5514==      possibly lost: 0 bytes in 0 blocks
==5514==    still reachable: 0 bytes in 0 blocks
==5514==         suppressed: 0 bytes in 0 blocks
==5514==
==5514== For counts of detected and suppressed errors, rerun with: -v
==5514== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
]0;namir@namir: ~/lab8[01;32mnamir@namir[00m:[01;34m~/lab8[00m$ exit
exit

Script done on Wed 12 Apr 2017 09:02:57 AM PDT
